/* Form Filler – locale datasets (Italian, US English, UK English). All values are fictitious test data. */
(() => {
  'use strict';
  const FF = globalThis.__FF;
  if (!FF || FF.data) return;

  // code = Belfiore cadastral code (used by the codice fiscale), tel = area prefix
  const IT_CITIES = [
    ['Roma', 'RM', 'Roma', 'Lazio', '00184', 'H501', '06', 41.9028, 12.4964],
    ['Milano', 'MI', 'Milano', 'Lombardia', '20121', 'F205', '02', 45.4642, 9.19],
    ['Napoli', 'NA', 'Napoli', 'Campania', '80133', 'F839', '081', 40.8518, 14.2681],
    ['Torino', 'TO', 'Torino', 'Piemonte', '10121', 'L219', '011', 45.0703, 7.6869],
    ['Palermo', 'PA', 'Palermo', 'Sicilia', '90133', 'G273', '091', 38.1157, 13.3615],
    ['Genova', 'GE', 'Genova', 'Liguria', '16121', 'D969', '010', 44.4056, 8.9463],
    ['Bologna', 'BO', 'Bologna', 'Emilia-Romagna', '40121', 'A944', '051', 44.4949, 11.3426],
    ['Firenze', 'FI', 'Firenze', 'Toscana', '50122', 'D612', '055', 43.7696, 11.2558],
    ['Bari', 'BA', 'Bari', 'Puglia', '70121', 'A662', '080', 41.1171, 16.8719],
    ['Catania', 'CT', 'Catania', 'Sicilia', '95121', 'C351', '095', 37.5079, 15.083],
    ['Venezia', 'VE', 'Venezia', 'Veneto', '30121', 'L736', '041', 45.4408, 12.3155],
    ['Verona', 'VR', 'Verona', 'Veneto', '37121', 'L781', '045', 45.4384, 10.9916],
    ['Padova', 'PD', 'Padova', 'Veneto', '35121', 'G224', '049', 45.4064, 11.8768],
    ['Trieste', 'TS', 'Trieste', 'Friuli-Venezia Giulia', '34121', 'L424', '040', 45.6495, 13.7768],
    ['Brescia', 'BS', 'Brescia', 'Lombardia', '25121', 'B157', '030', 45.5416, 10.2118],
    ['Parma', 'PR', 'Parma', 'Emilia-Romagna', '43121', 'G337', '0521', 44.8015, 10.3279],
    ['Modena', 'MO', 'Modena', 'Emilia-Romagna', '41121', 'F257', '059', 44.6471, 10.9252],
    ['Perugia', 'PG', 'Perugia', 'Umbria', '06121', 'G478', '075', 43.1107, 12.3908],
    ['Cagliari', 'CA', 'Cagliari', 'Sardegna', '09124', 'B354', '070', 39.2238, 9.1217],
    ['Pisa', 'PI', 'Pisa', 'Toscana', '56125', 'G702', '050', 43.7228, 10.4017],
    ['Bergamo', 'BG', 'Bergamo', 'Lombardia', '24121', 'A794', '035', 45.6983, 9.6773],
    ['Como', 'CO', 'Como', 'Lombardia', '22100', 'C933', '031', 45.8081, 9.0852],
    ['Ancona', 'AN', 'Ancona', 'Marche', '60121', 'A271', '071', 43.6158, 13.5189],
    ['Trento', 'TN', 'Trento', 'Trentino-Alto Adige', '38122', 'L378', '0461', 46.0748, 11.1217],
    ['Bolzano', 'BZ', 'Bolzano', 'Trentino-Alto Adige', '39100', 'A952', '0471', 46.4983, 11.3548],
    ['Lecce', 'LE', 'Lecce', 'Puglia', '73100', 'E506', '0832', 40.3515, 18.175],
    ['Salerno', 'SA', 'Salerno', 'Campania', '84121', 'H703', '089', 40.6824, 14.7681],
    ['Rimini', 'RN', 'Rimini', 'Emilia-Romagna', '47921', 'H294', '0541', 44.0678, 12.5695],
    ['Siena', 'SI', 'Siena', 'Toscana', '53100', 'I726', '0577', 43.3188, 11.3308],
    ['Udine', 'UD', 'Udine', 'Friuli-Venezia Giulia', '33100', 'L483', '0432', 46.0711, 13.2346],
    ['Messina', 'ME', 'Messina', 'Sicilia', '98122', 'F158', '090', 38.1938, 15.554],
    ['Pescara', 'PE', 'Pescara', 'Abruzzo', '65121', 'G482', '085', 42.4618, 14.2161],
  ].map(([name, prov, provName, region, cap, code, tel, lat, lon]) => ({
    name, prov, provName, region, cap, code, tel, lat, lon,
  }));

  const US_CITIES = [
    ['New York', 'NY', 'New York', '10001', '212', 40.7128, -74.006],
    ['Los Angeles', 'CA', 'California', '90012', '213', 34.0522, -118.2437],
    ['Chicago', 'IL', 'Illinois', '60601', '312', 41.8781, -87.6298],
    ['Houston', 'TX', 'Texas', '77002', '713', 29.7604, -95.3698],
    ['Phoenix', 'AZ', 'Arizona', '85004', '602', 33.4484, -112.074],
    ['Philadelphia', 'PA', 'Pennsylvania', '19103', '215', 39.9526, -75.1652],
    ['San Diego', 'CA', 'California', '92101', '619', 32.7157, -117.1611],
    ['Dallas', 'TX', 'Texas', '75201', '214', 32.7767, -96.797],
    ['Austin', 'TX', 'Texas', '78701', '512', 30.2672, -97.7431],
    ['Seattle', 'WA', 'Washington', '98101', '206', 47.6062, -122.3321],
    ['Denver', 'CO', 'Colorado', '80202', '303', 39.7392, -104.9903],
    ['Boston', 'MA', 'Massachusetts', '02108', '617', 42.3601, -71.0589],
    ['Miami', 'FL', 'Florida', '33130', '305', 25.7617, -80.1918],
    ['Atlanta', 'GA', 'Georgia', '30303', '404', 33.749, -84.388],
    ['Portland', 'OR', 'Oregon', '97204', '503', 45.5152, -122.6784],
    ['San Francisco', 'CA', 'California', '94103', '415', 37.7749, -122.4194],
  ].map(([name, prov, provName, cap, tel, lat, lon]) => ({
    name, prov, provName, region: provName, cap, code: 'Z404', tel, lat, lon,
  }));

  const UK_CITIES = [
    ['London', 'Greater London', 'England', 'EC1A 1BB', '020', 51.5074, -0.1278],
    ['Manchester', 'Greater Manchester', 'England', 'M1 1AE', '0161', 53.4808, -2.2426],
    ['Birmingham', 'West Midlands', 'England', 'B1 1AA', '0121', 52.4862, -1.8904],
    ['Leeds', 'West Yorkshire', 'England', 'LS1 4AP', '0113', 53.8008, -1.5491],
    ['Liverpool', 'Merseyside', 'England', 'L1 8JQ', '0151', 53.4084, -2.9916],
    ['Bristol', 'Bristol', 'England', 'BS1 4DJ', '0117', 51.4545, -2.5879],
    ['Edinburgh', 'City of Edinburgh', 'Scotland', 'EH1 1YZ', '0131', 55.9533, -3.1883],
    ['Glasgow', 'Glasgow City', 'Scotland', 'G1 1XQ', '0141', 55.8642, -4.2518],
    ['Cardiff', 'Cardiff', 'Wales', 'CF10 1EP', '029', 51.4816, -3.1791],
    ['Oxford', 'Oxfordshire', 'England', 'OX1 1BX', '01865', 51.752, -1.2577],
    ['Cambridge', 'Cambridgeshire', 'England', 'CB2 1TN', '01223', 52.2053, 0.1218],
  ].map(([name, county, region, cap, tel, lat, lon]) => ({
    name, prov: county, provName: county, region, cap, code: 'Z114', tel, lat, lon,
  }));

  const EN_COMMON = {
    male: ['James', 'John', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Thomas', 'Daniel', 'Matthew',
      'Oliver', 'Harry', 'George', 'Jack', 'Henry', 'Samuel', 'Benjamin', 'Andrew', 'Joseph', 'Charles'],
    female: ['Mary', 'Emma', 'Olivia', 'Sophia', 'Emily', 'Charlotte', 'Amelia', 'Jessica', 'Sarah', 'Elizabeth',
      'Hannah', 'Grace', 'Lucy', 'Chloe', 'Alice', 'Megan', 'Laura', 'Rachel', 'Anna', 'Isabella'],
    last: ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Miller', 'Davis', 'Wilson', 'Taylor', 'Anderson',
      'Thomas', 'Moore', 'Martin', 'Jackson', 'Thompson', 'White', 'Harris', 'Clark', 'Lewis', 'Walker',
      'Hall', 'Young', 'King', 'Wright', 'Scott', 'Green', 'Baker', 'Adams', 'Turner', 'Parker'],
    streets: ['Main Street', 'Oak Avenue', 'Maple Drive', 'Park Road', 'High Street', 'Church Lane', 'Elm Street',
      'Cedar Lane', 'Washington Avenue', 'Station Road', 'Victoria Road', 'Mill Lane', 'Pine Street', 'King Street'],
    companyWords: ['Global', 'Northwind', 'Blue Harbor', 'Summit', 'Bright', 'Pioneer', 'Silverline', 'Evergreen'],
    jobs: ['Software Engineer', 'Product Manager', 'Accountant', 'Sales Manager', 'Consultant', 'Data Analyst',
      'Graphic Designer', 'Teacher', 'Marketing Specialist', 'Project Manager', 'Office Administrator'],
    departments: ['Sales', 'IT', 'Human Resources', 'Finance', 'Marketing', 'Operations', 'Customer Service'],
    education: ["Bachelor's degree", 'Bachelor', 'Degree', 'University', 'College', "Master's degree", 'High school'],
    sentences: [
      'This is an automatically generated test message.',
      'I would like to receive more information about your services.',
      'This form was filled in for testing purposes only.',
      'Please feel free to ignore this test submission.',
      'Thank you for your time and attention.',
      'The delivery is expected by the end of the month.',
      'I am looking forward to hearing from you soon.',
      'Could you please send me a quote for the items listed above?',
      'Kind regards.',
    ],
    subjects: ['Information request', 'Test message', 'Contact form test', 'Question about your services', 'Quote request'],
    words: ['test', 'sample', 'example', 'check', 'value', 'demo', 'trial', 'project', 'request', 'service'],
    objectWords: ['Alpha', 'Beta', 'Gamma', 'Delta', 'Omega'],
    searches: ['test', 'shoes', 'offers', 'laptop', 'contact'],
    colors: ['Blue', 'Red', 'Green', 'Black', 'White'],
    coupon: ['TEST10', 'WELCOME10'],
    months: ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december'],
    language: ['English', 'Inglese', 'en', 'EN', 'ENG'],
    marital: ['Single', 'Never married', 'Unmarried', 'Celibe/Nubile'],
    // Banking
    paymentRefs: ['INV {n} {year}', 'Invoice {n}', 'Test payment', 'Rent {month}'],
    loanPurposes: ['Car purchase', 'Home improvements', 'Debt consolidation', 'Wedding', 'Other'],
    fundsSources: ['Employment income', 'Salary', 'Employment', 'Wages', 'Savings'],
    accountPurposes: ['Everyday banking', 'Day-to-day spending', 'Personal use', 'Salary', 'Savings'],
    employment: ['Employed full-time', 'Employed (full-time)', 'Full-time employed', 'Employed', 'Full-time', 'Full time'],
    accountTypes: ['Current account', 'Personal current account', 'Personal', 'Checking', 'Personal checking', 'Individual'],
    securityQuestion: ['What was the name of your first pet?'],
    memorable: ['sunflower', 'rainbow', 'mountain', 'butterfly', 'horizon'],
  };

  FF.data = {
    it: {
      male: ['Marco', 'Luca', 'Giuseppe', 'Alessandro', 'Andrea', 'Francesco', 'Matteo', 'Lorenzo', 'Davide', 'Simone',
        'Federico', 'Riccardo', 'Stefano', 'Paolo', 'Giovanni', 'Antonio', 'Roberto', 'Fabio', 'Daniele', 'Gabriele'],
      female: ['Giulia', 'Francesca', 'Chiara', 'Sara', 'Martina', 'Valentina', 'Alessia', 'Elena', 'Federica', 'Silvia',
        'Laura', 'Anna', 'Elisa', 'Giorgia', 'Sofia', 'Aurora', 'Paola', 'Roberta', 'Ilaria', 'Beatrice'],
      last: ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco',
        'Bruno', 'Gallo', 'Conti', 'De Luca', 'Mancini', 'Costa', 'Giordano', 'Rizzo', 'Lombardi', 'Moretti',
        'Barbieri', 'Fontana', 'Santoro', 'Mariani', 'Rinaldi', 'Caruso', 'Ferrara', 'Galli', 'Martini', 'Leone'],
      cities: IT_CITIES,
      streets: ['Via Roma', 'Via Garibaldi', 'Corso Italia', 'Via Dante Alighieri', 'Piazza Duomo', 'Via Mazzini',
        'Via Giuseppe Verdi', 'Viale Europa', 'Via Cavour', 'Corso Vittorio Emanuele II', 'Via Guglielmo Marconi',
        'Via XX Settembre', 'Via Alessandro Manzoni', 'Via Giacomo Leopardi', 'Via dei Mille'],
      companyWords: ['Tecnologie', 'Servizi', 'Sistemi', 'Soluzioni', 'Logistica', 'Costruzioni', 'Consulting', 'Informatica'],
      companySuffix: ['S.r.l.', 'S.p.A.', 'S.n.c.', 'S.a.s.', 'S.r.l.s.'],
      jobs: ['Impiegato amministrativo', 'Sviluppatore software', 'Ingegnere', 'Consulente', 'Commerciale',
        'Responsabile acquisti', 'Project manager', 'Analista', 'Insegnante', 'Architetto', 'Grafico'],
      departments: ['Amministrazione', 'Vendite', 'IT', 'Risorse Umane', 'Marketing', 'Logistica', 'Assistenza clienti'],
      education: ['Laurea', 'Laurea magistrale', 'Laurea triennale', 'Diploma', 'Diploma di maturità', "Bachelor's degree"],
      sentences: [
        'Questo è un messaggio di prova generato automaticamente.',
        'Vorrei ricevere maggiori informazioni sui vostri servizi.',
        'Il modulo è stato compilato esclusivamente a scopo di test.',
        'Si prega di ignorare questa richiesta di prova.',
        'Grazie per la cortese attenzione.',
        'La consegna è prevista entro la fine del mese.',
        'Resto in attesa di un vostro gentile riscontro.',
        'Potreste inviarmi un preventivo per gli articoli indicati?',
        'Cordiali saluti.',
      ],
      subjects: ['Richiesta informazioni', 'Messaggio di prova', 'Test modulo di contatto', 'Informazioni sui servizi', 'Richiesta preventivo'],
      words: ['prova', 'esempio', 'campione', 'verifica', 'valore', 'collaudo', 'controllo', 'progetto', 'richiesta', 'servizio'],
      objectWords: ['Alfa', 'Beta', 'Gamma', 'Delta', 'Omega'],
      searches: ['prova', 'scarpe', 'offerte', 'portatile', 'contatti'],
      colors: ['Blu', 'Rosso', 'Verde', 'Nero', 'Bianco'],
      coupon: ['TEST10', 'BENVENUTO10'],
      months: ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
      country: ['Italia', 'Italy', 'IT', 'ITA', 'Repubblica Italiana'],
      nationality: ['Italiana', 'Italiano', 'Italian', 'Italia', 'Italy', 'IT', 'ITA'],
      language: ['Italiano', 'Italian', 'it', 'IT', 'ITA'],
      marital: ['Celibe/Nubile', 'Libero', 'Single', 'Non coniugato'],
      dial: '+39',
      mobilePrefixes: ['320', '328', '333', '335', '338', '339', '340', '345', '347', '349', '366', '371', '388', '392'],
      banks: [
        { abi: '03069', bic: 'BCITITMM', name: 'Intesa Sanpaolo' },
        { abi: '02008', bic: 'UNCRITMM', name: 'UniCredit' },
        { abi: '05034', bic: 'BAPPIT21', name: 'Banco BPM' },
        { abi: '01030', bic: 'PASCITMM', name: 'Banca Monte dei Paschi di Siena' },
        { abi: '05696', bic: 'POSOIT22', name: 'Banca Popolare di Sondrio' },
        { abi: '03062', bic: 'MEDBITMM', name: 'Banca Mediolanum' },
      ],
      domain: 'example.it',
      // Banking
      paymentRefs: ['Pagamento fattura n. {n}/{year}', 'Saldo fattura {n}', 'Bonifico di prova', 'Rimborso spese {month}'],
      loanPurposes: ['Acquisto auto', 'Ristrutturazione casa', 'Acquisto prima casa', 'Consolidamento debiti', 'Spese personali', 'Altro'],
      fundsSources: ['Reddito da lavoro dipendente', 'Lavoro dipendente', 'Stipendio', 'Redditi da lavoro', 'Risparmi', 'Employment income', 'Salary'],
      accountPurposes: ['Accredito stipendio', 'Gestione delle spese personali', 'Gestione spese quotidiane', 'Operatività quotidiana', 'Risparmio', 'Everyday banking'],
      employment: ['Dipendente a tempo indeterminato', 'Lavoratore dipendente', 'Dipendente', 'Impiegato', 'Employed full-time', 'Employed'],
      accountTypes: ['Conto corrente', 'Conto personale', 'Privato', 'Persona fisica', 'Current account', 'Personal'],
      currency: ['EUR', 'Euro', '€'],
      securityQuestion: ['Qual è il nome del tuo primo animale domestico?'],
      memorable: ['girasole', 'arcobaleno', 'montagna', 'farfalla', 'orizzonte'],
    },
    'en-US': {
      ...EN_COMMON,
      cities: US_CITIES,
      country: ['United States', 'United States of America', 'USA', 'US', 'Stati Uniti'],
      nationality: ['American', 'United States', 'USA', 'US'],
      companySuffix: ['Inc.', 'LLC', 'Corp.', 'Group', 'Industries'],
      dial: '+1',
      banks: [
        { bic: 'CHASUS33', name: 'JPMorgan Chase Bank' },
        { bic: 'BOFAUS3N', name: 'Bank of America' },
        { bic: 'CITIUS33', name: 'Citibank' },
      ],
      currency: ['USD', 'US Dollar', 'Dollar', '$'],
      domain: 'example.com',
    },
    'en-GB': {
      ...EN_COMMON,
      cities: UK_CITIES,
      country: ['United Kingdom', 'UK', 'GB', 'GBR', 'Great Britain', 'Regno Unito'],
      nationality: ['British', 'United Kingdom', 'UK', 'GB', 'GBR'],
      companySuffix: ['Ltd', 'Limited', 'PLC', 'Group', '& Co.'],
      dial: '+44',
      banks: [
        { code: 'NWBK', bic: 'NWBKGB2L', name: 'NatWest' },
        { code: 'BARC', bic: 'BARCGB22', name: 'Barclays' },
        { code: 'LOYD', bic: 'LOYDGB2L', name: 'Lloyds Bank' },
        { code: 'HBUK', bic: 'HBUKGB4B', name: 'HSBC UK' },
        { code: 'MIDL', bic: 'MIDLGB22', name: 'HSBC Bank' },
      ],
      currency: ['GBP', 'Pound sterling', 'British Pound', 'Sterling', '£'],
      domain: 'example.co.uk',
    },
  };

  // Well-known payment-gateway test cards (Luhn-valid, never real accounts).
  FF.TEST_CARDS = [
    { brand: 'Visa', number: '4111111111111111', cvvLen: 3 },
    { brand: 'Visa', number: '4242424242424242', cvvLen: 3 },
    { brand: 'Mastercard', number: '5555555555554444', cvvLen: 3 },
    { brand: 'Mastercard', number: '5105105105105100', cvvLen: 3 },
  ];
})();
